### ISSUE TITLE
Apply Spring 4 & IO Platform

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-tourreservation#114]
see terasolunaorg/terasoluna-gfw#132 & terasolunaorg/terasoluna-gfw#178.
- [x] Modify pom files. #117 
- [x] Modify to use class of tiles3 (in spring-mvc.xml) #117 
- [x] Modify to use dtd of tiles3 (in tiles-definitions.xml) #117
- [x] Add tags-tiles-extras(jsp tag library) in `include.jsp` #117
- [x] Modify as manage scope of libraries by parent project. #117 
- [x] Apply Commons-dbcp2. #117
- [x] Update jdbc driver of postgresql.  #117
- [x] Update jdbc driver of postgresql in selenium project. (Corresponding leakage of #117)  #118
- [x] Confirm modification necessity associated with version up of Joda-Time. And  if necessary, please modify.
- [x] Confirm modification necessity associated with spec-change of `@ControllerAdvice`. And  if necessary, please modify.
- [x] Confirm modification necessity associated with version up of Bean Validation. And  if necessary, please modify.
- [x]  Apply namespace of ViewResolver #143
